name: chronostrain_full

channels:
  - conda-forge
  - bioconda
  - pytorch

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - numba
  - intervaltree
  - jax
  - jaxlib=*=*cuda*
  - cuda-nvcc
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - biopython
  - click
  - samtools=1.14
  - mafft
  - bwa
  - bwa-mem2
  - bowtie2
  - cdbtools
  - pigz
  - blast
  - fasttree
  - sra-tools=2.11
  - kneaddata
  - trimmomatic
  - strainge
  - fastmlst
  - pip:
    - ./