name: chronostrain_basic

channels:
  - conda-forge
  - bioconda
  - nvidia

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - numba
  - intervaltree
  - jax
  - jaxlib=*=*cuda*
  - cuda-nvcc
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - biopython
  - click
  - samtools=1.14
  - mafft
  - bwa
  - bwa-mem2
  - bowtie2
  - cdbtools
  - pigz
  - pip:
    - ./