name: chronostrain_basic

channels:
  - conda-forge
  - bioconda
  - nvidia

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - pyarrow
  - numba
  - intervaltree
  - jax
  - jaxlib=*=*cuda*
  - optax
  - cuda-nvcc
  - scikit-learn
  - matplotlib
  - seaborn
  - biopython
  - click
  - blast
  - samtools
  - mafft
  - bwa
  - bwa-mem2
  - bowtie2
  - cdbtools
  - pip:
    - ./